### ISSUE TITLE
[feature request] Icon size standardization

### ISSUE THREAD

**Issue by nascentt** [altlimit/applauncher#1]
DIfferent apps seem to have different icons sizes (and shapes).  
![applauncher-iconsizes](https://github.com/altlimit/applauncher/assets/1145722/95801e38-5f08-4d70-a89d-97b05d2d963b)

I know launchers like Nova have functionality like setting forced icons size and shape, but this likely will be too involved.  However, there might be an easier way for you to limit the object size within the grids to standardize the sizes?

Figured I'd request it if there is an easy way to achieve it.

**Comment by faisalraja** [comment]
Check if this is fixed in release c7a6d64

**Comment by nascentt** [comment]
Yup perfect. Thank you!
