### ISSUE TITLE
[feature request] Controller navigation

### ISSUE THREAD

**Issue by nascentt** [altlimit/applauncher#2]
It'd be great (if at all feasible) to be able to navigate AppLauncher via controller.  Specifically the navigation via directional pad and launch of an app via button press.

**Comment by faisalraja** [comment]
Check this on release c7a6d64 see if it works, I only use Arrow *keys* and Enter, I'm not sure if that's the same keys for D-Pad and X button or enter. Maybe it needs to be mapped, if it doesn't work, then I need to get it to use the correct keys.

**Comment by nascentt** [comment]
Dpad and analog stick work great.
Joypad button can select the sidebar and categories within it.
Currently no ability to launch apps with controller though.
Also navigating out of view doesn't scroll down the view. If having the view auto scroll to selection is too hard having the right analogue stick handle scroll might be easier.

Also sometimes the navigation gets stuck on the first two rows only and it's not possible to scroll down to the 3rd row.  Going to sidebar and back out fixes. Maybe the navigation area is set whilst the rows are still loading or something.

Many thanks for this implementation so far.

**Comment by faisalraja** [comment]
Check if latest version fixes the issues. Also in settings, set a Launch key to allow launching apps from controller other than the "Enter" key.

**Comment by nascentt** [comment]
Amazing.  Indeed apps now launch. The setting is also a nice touch.

Many thanks

**Comment by nascentt** [comment]
Amazing.  Indeed apps now launch. The setting  to choose whichever button you want is a nice touch.

Many thanks.

Also many thanks for fixing the scrolling!

Edit: I do get the weird issue with not being able to scroll past certain rows sometimes, but it's easy to work around by navigating to the side menu then back.
Can log it as a separate issue if you'd prefer.

**Comment by faisalraja** [comment]
If you can create a separate issue with steps steps to duplicate the issue consistently would be great. Thanks
