### ISSUE TITLE
Unable to scroll through all rows sometimes 

### ISSUE THREAD

**Issue by nascentt** [altlimit/applauncher#4]
I'll add more information later if I'm able to narrow down what's happening.

But essentially sometimes when scrolling through the apps with a controller, I am unable to scroll past a particular row to get to the apps below it.

To workaround the issue I can navigate to the side menu then go back into the category and then can scroll through all rows.

(Stems from https://github.com/altlimit/applauncher/issues/2)
If I had to guess, the navigation area or the navigation row count is less than the actual amount.

I'll see if I can find a way to reproduce it on demand.

**Comment by faisalraja** [comment]
Fixed.

**Comment by nascentt** [comment]
It does indeed seem fixed, I haven't been able to reproduce it.

Many thanks!
